config/routes.rb
Rails.application.routes.draw do
  draw :emailings
  resources :meetings
  draw :owners
  draw :budgets
  draw :hoas
  draw :base
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :hoa
  validates :name, :start_time, :days, presence: true
  has_rich_text :summary
  has_rich_text :location

  default_scope { order(start_time: :desc) }

  def pdf_name
    "ag_#{self.name}_#{self.hoa.name}.pdf"
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  def index
    @meetings = Meeting.all    
  end

  def new
    @meeting = Meeting.new
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = MeetingPdf.new(@meeting)
        send_data pdf.render, 
          filename: @meeting.pdf_name, 
          type: "application/pdf", 
          disposition: "inline"
      end
    end
  end

  def edit
    
  end

  def create
    @meeting = Meeting.create(meeting_params)
    redirect_to @meeting, notice: "Assemblée générale ajoutée avec succès !"
  end

  def update
    @meeting.update(meeting_params)
    redirect_to @meeting, notice: "Assemblée générale modifiée avec succès !"
  end

  def destroy
    @meeting.destroy
    redirect_to meetings_path, notice: "Assemblée générale supprimée avec succès !"
  end

  private

  def meeting_params
    params.require(:meeting).permit(
      :name,
      :start_time,
      :summary,
      :location,
      :hoa_id,
      :days
    )
  end

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end
end

app/views/meetings/_form.html.erb
<%= form_with model: meeting, builder: CustomFormBuilder do |form| %>
  <%= render "shared/errors", object: form.object %>

  <%= form.text_field :name, autofocus: true %>
  <%= form.collection_select :hoa_id, current_user.hoas, :id, :name %>
  <%= form.datetime_field :start_time %>
  <%= form.number_field :days %>
  
  <%= form.label :summary %>
  <%= form.rich_text_area :summary %>

  <br />
  <%= form.label :location %>
  <%= form.rich_text_area :location %>
  <%= form.submit %>

<% end %>

app/views/meetings/_meeting.html.erb
<%= content_tag :li, id: dom_id(meeting), class: "bg-slate-900 group rounded-xl p-4 border border-slate-900 hover:border-indigo-500" do %>
  <div class="flex items-center justify-between">
    <div class="flex flex-col space-y-2">
      <div class="">
        <%= meeting.name %>
      </div>
      <div class="text-xs text-gray-400"><%= l(meeting.start_time) %></div>
    </div>
    
    <div>
      <%= link_to meeting do %>
        <svg class="size-8 opacity-30 group-hover:opacity-100 transition-opacity" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14" height="14" width="14"><g id="location-building-search"><path id="Vector" fill="#a7f3d0" d="M6.64 12.28c3.61 0 5.64 -2.03 5.64 -5.64S10.25 1 6.64 1 1 3.03 1 6.64s2.03 5.64 5.64 5.64Z" stroke-width="1"></path><path id="Vector_2" stroke="#10b981" stroke-linecap="round" stroke-linejoin="round" d="M6.64 12.28c3.61 0 5.64 -2.03 5.64 -5.64S10.25 1 6.64 1 1 3.03 1 6.64s2.03 5.64 5.64 5.64Z" stroke-width="1"></path><path id="Vector_3" stroke="#10b981" stroke-linecap="round" stroke-linejoin="round" d="m13 13 -2.146 -2.146" stroke-width="1"></path><path id="Vector 1889" fill="#ffffff" d="M4.14 8.64v-2.5c0.762 -1.195 1.324 -1.718 2.5 -2.5 1.176 0.782 1.738 1.305 2.5 2.5v2.5a0.5 0.5 0 0 1 -0.5 0.5h-4a0.5 0.5 0 0 1 -0.5 -0.5Z" stroke-width="1"></path><path id="Vector 1936" stroke="#10b981" stroke-linecap="round" stroke-linejoin="round" d="M6.64 9.14v-1.5" stroke-width="1"></path><path id="Vector 1937" stroke="#10b981" stroke-linecap="round" stroke-linejoin="round" d="M4.14 8.64v-2.5c0.762 -1.195 1.324 -1.718 2.5 -2.5 1.176 0.782 1.738 1.305 2.5 2.5v2.5a0.5 0.5 0 0 1 -0.5 0.5h-4a0.5 0.5 0 0 1 -0.5 -0.5Z" stroke-width="1"></path></g></svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<% content_for :title do %>
  <%= render TitleComponent.new title: "Modifier l'assemblée", 
    subtitle: "Renseignez les informations suivantes :" %>
<% end %>

<% content_for :back_button, render(BackButtonComponent.new) %>

<%= render 'form', meeting: @meeting %>

app/views/meetings/index.html.erb
<% content_for :title do %>
  <%= render TitleComponent.new title: "Liste des Assemblées générales", subtitle: "Retrouvez ici la liste de vos assemblées générales." %>
<% end %>

<div class="mt-10"><%= render LinkComponent.new name: "Ajouter un assemblée", url: new_meeting_path %></div>

<ul id="meetings" class="mt-10 flex flex-col space-y-2">
  <%= render @meetings %>
</ul>

app/views/meetings/new.html.erb
<% content_for :title do %>
  <%= render TitleComponent.new title: "Nouvelle assemblée", 
    subtitle: "Renseignez les informations suivantes :" %>
<% end %>

<% content_for :back_button, render(BackButtonComponent.new) %>

<%= render 'form', meeting: @meeting %>

app/views/meetings/show.html.erb
<% content_for :title do %>
  <%= render TitleComponent.new title: "AG du #{l(@meeting.start_time, format: :short)}", subtitle: @meeting.name %>
<% end %>

<% content_for :back_button, render(BackButtonComponent.new) %>
<% content_for :edit_button, render(EditButtonComponent.new(url: edit_meeting_path(@meeting))) %>

<h3 class="text-xl text-slate-400 mb-4 pb-4 border-b">Ordre du jour</h3>
<%= @meeting.summary %>

<h3 class="text-xl text-slate-400 mb-4 pb-4 border-b">Lieu de la réunion</h3>
<%= @meeting.location %>

<div class="mt-6 flex justify-between items-center">
  <%= link_to "&larr; revenir à la liste des assemblées".html_safe, meetings_path, class: "text-slate-400" %>
  <%= link_to meeting_path(@meeting, format: :pdf), target: "_blank" do %>
    <svg class="size-10 hover:opacity-80" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="File-Pdf-1--Streamline-Ultimate"><desc>File Pdf 1 Streamline Icon: https://streamlinehq.com</desc><g><path d="M11.46 12.26c-0.2 -0.07 -0.34 0 -0.34 0.17v6c0 0.24 0.19 0.35 0.45 0.26a3.38 3.38 0 0 0 -0.11 -6.44Z" fill="currentcolor" stroke-width="1"></path><path d="M6.5 12.12H5.37a0.25 0.25 0 0 0 -0.25 0.25v2.25a0.25 0.25 0 0 0 0.25 0.25H6.5a1.38 1.38 0 0 0 0 -2.75Z" fill="currentcolor" stroke-width="1"></path><path d="M22.5 0h-21A1.5 1.5 0 0 0 0 1.5v21A1.5 1.5 0 0 0 1.5 24h21a1.5 1.5 0 0 0 1.5 -1.5v-21A1.5 1.5 0 0 0 22.5 0Zm-16 16.12H5.37a0.25 0.25 0 0 0 -0.25 0.25v3.13a0.62 0.62 0 0 1 -1.24 0v-8a0.63 0.63 0 0 1 0.62 -0.63h2a2.63 2.63 0 0 1 0 5.25Zm4 4a0.63 0.63 0 0 1 -0.63 -0.62v-8a0.63 0.63 0 0 1 0.63 -0.63 4.63 4.63 0 0 1 0 9.25Zm10 -8H18a0.89 0.89 0 0 0 -0.88 0.88v1.62a0.25 0.25 0 0 0 0.25 0.25H19a0.63 0.63 0 0 1 0 1.25h-1.63a0.25 0.25 0 0 0 -0.25 0.25v3.13a0.62 0.62 0 0 1 -0.62 0.62 0.63 0.63 0 0 1 -0.63 -0.62V13A2.14 2.14 0 0 1 18 10.87h2.5a0.63 0.63 0 0 1 0 1.25Z" fill="currentcolor" stroke-width="1"></path></g></svg>
  <% end %>
</div>